name: Android CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run lint
        run: ./gradlew lintDebug
      - name: Upload test report artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: Building via Gradle..
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
