name: Android CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run lint
        run: ./gradlew lintDebug
      - name: Upload test report artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4
      - name: Setup JDK 11
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: SonarCloud scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup JDK 11
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt-openj9
      - name: Building via Gradle..
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: Inventa.apk
          path: app/build/outputs/apk/debug/app-debug.apk
